app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_client_all:
    pattern:  /client
    defaults: { _controller: AppBundle:Client:all, _format: ~ }
    requirements:
        _method: GET

app_client_get:
    pattern:  /client/{id}
    defaults: { _controller: AppBundle:Client:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

app_client_new:
    pattern:  /client
    defaults: { _controller: AppBundle:Client:create, _format: ~ }
    requirements:
        _method: POST

app_client_delete:
    pattern:  /client/{id}
    defaults: { _controller: AppBundle:Client:delete, _format: ~ }
    requirements:
        _method: DELETE

app_client_update:
    pattern:  /client/{id}
    defaults: { _controller: AppBundle:Client:update, _format: ~ }
    requirements:
        _method: PUT
